In [14]:
import os

path = '../data/raw_data/ecommerce_pricing_raw_data.csv'
print("File exists:", os.path.exists(path))

File exists: True

In [15]:
import pandas as pd

df = pd.read_csv('../data/raw_data/ecommerce_pricing_raw_data.csv')
df.head()

,date,product_id,category,price,cost,discount_pct,units_sold,revenue,inventory_level,competitor_price,season,day_of_week
0,01-01-2024,P100,Home,954.0,674.89,10,1,954.0,141,963.24,Normal,Monday
1,01-01-2024,P101,Sports,280.5,199.36,15,6,1683.0,313,289.83,Normal,Monday
2,01-01-2024,P102,Electronics,659.0,476.02,0,0,0.0,494,627.57,Festival,Monday
3,01-01-2024,P103,Fashion,1157.0,875.89,0,0,0.0,339,1158.65,Normal,Monday
4,01-01-2024,P104,Home,220.0,151.82,0,6,1320.0,33,229.73,Sale,Monday

In [16]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7300 entries, 0 to 7299
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              7300 non-null   object
 1   product_id        7300 non-null   object
 2   category          7300 non-null   object
 3   price             7300 non-null   float64
 4   cost              7300 non-null   float64
 5   discount_pct      7300 non-null   int64
 6   units_sold        7300 non-null   int64
 7   revenue           7300 non-null   float64
 8   inventory_level   7300 non-null   int64
 9   competitor_price  7300 non-null   float64
 10  season            7300 non-null   object
 11  day_of_week       7300 non-null   object
dtypes: float64(4), int64(3), object(5)
memory usage: 684.5+ KB

,price,cost,discount_pct,units_sold,revenue,inventory_level,competitor_price
count,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000
mean,810.989267,594.242686,4.565068,1.763699,1128.634568,262.911644,811.243141
std,361.084406,267.659533,5.230593,1.917156,1272.581029,139.656189,362.129775
min,170.000000,124.030000,0.000000,0.000000,0.000000,20.000000,163.010000
25%,501.225000,364.000000,0.000000,0.000000,0.000000,141.000000,501.325000
50%,806.775000,592.590000,5.000000,1.000000,887.400000,264.000000,808.610000
75%,1115.000000,819.355000,10.000000,3.000000,1734.000000,385.000000,1110.972500
max,1499.000000,1194.430000,15.000000,11.000000,8904.000000,499.000000,1571.900000

In [17]:
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

In [18]:
df['profit'] = df['revenue'] - (df['cost'] * df['units_sold'])
df['margin_pct'] = df['profit'] / df['revenue']
df['price_diff_competitor'] = df['price'] - df['competitor_price']

In [19]:
df.to_csv('../data/processed_data/ecommerce_pricing_clean.csv', index=False)